name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./automation-exercise-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress (headless)
        run: npx cypress run --browser chrome --headless

      - name: Upload Cypress HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-html-report
          path: automation-exercise-test/cypress/reports
